apiVersion: v1
kind: Service
metadata:
  name: ai-analyzer
  namespace: vuln-benchmark
spec:
  selector:
    app: ai-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
